[CI] Force lit to use internal shell (#42)
**Issue:**  The following workflows fail due to Python lit API changes.

- build_and_test_triton_shared
- build_and_test_triton_shared_arm

```
Run python3 -m pip install lit
  python3 -m pip install lit
  LIT_TEST_DIR="build/$(ls build | grep -i cmake)/third_party/triton_shared/test"
  if [ ! -d "${LIT_TEST_DIR}" ]; then
    echo "Could not find '${LIT_TEST_DIR}'" ; exit -1
  fi
  lit -v "${LIT_TEST_DIR}"
  shell: /usr/bin/bash -e {0}
  env:
    PATH: /home/runner/.local/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Defaulting to user installation because normal site-packages is not writeable
Collecting lit
  Downloading lit-23.1.1-py3-none-any.whl.metadata (2.7 kB)
Downloading lit-23.1.1-py3-none-any.whl (111 kB)
Installing collected packages: lit
Successfully installed lit-23.1.1
lit: /home/runner/.local/lib/python3.12/site-packages/lit/TestingConfig.py:164: fatal: unable to parse config file '/home/runner/work/triton-shared/triton-shared/triton_shared/test/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/lit/TestingConfig.py", line 153, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/home/runner/work/triton-shared/triton-shared/triton_shared/test/lit.cfg.py", line 22, in <module>
    config.test_format = lit.formats.ShTest(not llvm_config.use_lit_shell)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/lit/formats/shtest.py", line 27, in __init__
    raise ValueError(
ValueError: execute_external=True is deprected as of LLVM-23 and the option will be removed in LLVM-24. Please move to using the internal shell (execute_external=False). If you still need to force external execution to allow time for migration, set force_execute_external=True

Error: Process completed with exit code 2.
```

E.g., See https://github.com/facebookincubator/triton-shared/pull/37
merge pipeline


**Fix :** Disable external shell execution

Signed-off-by: Tharindu Patabandi <tpataban@qti.qualcomm.com>